openapi: 3.0.4
info:
  contact:
    email: support@apibricks.io
    name: API BRICKS LTD
    url: https://www.coinapi.io
  license:
    name: MIT License
    url: https://github.com/api-bricks/api-bricks-sdk/blob/master/LICENSE
  title: CoinAPI Indexes REST API
  version: v1
servers:
- url: https://rest-api.indexes.coinapi.io
security:
- APIKey: []
- JWT: []
paths:
  /v1/indexes:
    get:
      responses:
        "200":
          content:
            text/plain:
              examples:
                Sample Index List:
                  value:
                  - id: IDX_REFRATE_VWAP_BTC
                  - id: IDX_REFRATE_VWAP_ETH
                  - id: IDX_REFRATE_VWAP_LTC
                  - id: IDX_REFRATE_VWAP_XRP
                  - id: IDX_REFRATE_VWAP_ADA
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexIdentifier"
                type: array
            application/json:
              examples:
                Sample Index List:
                  value:
                  - id: IDX_REFRATE_VWAP_BTC
                  - id: IDX_REFRATE_VWAP_ETH
                  - id: IDX_REFRATE_VWAP_LTC
                  - id: IDX_REFRATE_VWAP_XRP
                  - id: IDX_REFRATE_VWAP_ADA
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexIdentifier"
                type: array
            text/json:
              examples:
                Sample Index List:
                  value:
                  - id: IDX_REFRATE_VWAP_BTC
                  - id: IDX_REFRATE_VWAP_ETH
                  - id: IDX_REFRATE_VWAP_LTC
                  - id: IDX_REFRATE_VWAP_XRP
                  - id: IDX_REFRATE_VWAP_ADA
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexIdentifier"
                type: array
            application/x-msgpack:
              examples:
                Sample Index List:
                  value:
                  - id: IDX_REFRATE_VWAP_BTC
                  - id: IDX_REFRATE_VWAP_ETH
                  - id: IDX_REFRATE_VWAP_LTC
                  - id: IDX_REFRATE_VWAP_XRP
                  - id: IDX_REFRATE_VWAP_ADA
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexIdentifier"
                type: array
          description: successful operation
      summary: List indexes
      tags:
      - Indexes
  /v1/indexes/{index_id}/current:
    get:
      parameters:
      - explode: false
        in: path
        name: index_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                    timestamp: 2024-09-01T09:00:00
                    value: 56787.5997300339
              schema:
                $ref: "#/components/schemas/Models.IndexValue"
            application/json:
              examples:
                Example response:
                  value:
                    timestamp: 2024-09-01T09:00:00
                    value: 56787.5997300339
              schema:
                $ref: "#/components/schemas/Models.IndexValue"
            text/json:
              examples:
                Example response:
                  value:
                    timestamp: 2024-09-01T09:00:00
                    value: 56787.5997300339
              schema:
                $ref: "#/components/schemas/Models.IndexValue"
            application/x-msgpack:
              examples:
                Example response:
                  value:
                    timestamp: 2024-09-01T09:00:00
                    value: 56787.5997300339
              schema:
                $ref: "#/components/schemas/Models.IndexValue"
          description: successful operation
      summary: Current Index Value
      tags:
      - Indexes
  /v1/indexes/{index_definition_id}/currentSnapshot:
    get:
      parameters:
      - explode: false
        in: path
        name: index_definition_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
            application/x-msgpack:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
          description: successful operation
      summary: Current Index Values for index definition
      tags:
      - Indexes
  /v1/indexes/{index_id}/history:
    get:
      parameters:
      - explode: false
        in: path
        name: index_id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: time_start
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - explode: true
        in: query
        name: time_end
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                  - timestamp: 2024-09-05T11:29:04+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:03+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:02+00:00
                    value: 56786.84840020827
                    composition: []
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexValue"
                type: array
            application/json:
              examples:
                Example response:
                  value:
                  - timestamp: 2024-09-05T11:29:04+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:03+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:02+00:00
                    value: 56786.84840020827
                    composition: []
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexValue"
                type: array
            text/json:
              examples:
                Example response:
                  value:
                  - timestamp: 2024-09-05T11:29:04+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:03+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:02+00:00
                    value: 56786.84840020827
                    composition: []
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexValue"
                type: array
            application/x-msgpack:
              examples:
                Example response:
                  value:
                  - timestamp: 2024-09-05T11:29:04+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:03+00:00
                    value: 56786.84840020827
                    composition: []
                  - timestamp: 2024-09-05T11:29:02+00:00
                    value: 56786.84840020827
                    composition: []
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexValue"
                type: array
          description: successful operation
      summary: Historical Index Value w/Composition
      tags:
      - Indexes
  /v1/indexes/{index_definition_id}/historySnapshot:
    get:
      parameters:
      - explode: false
        in: path
        name: index_definition_id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: time
        required: false
        schema:
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
            application/x-msgpack:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexDefinitionSnapshotEntry"
                type: array
          description: successful operation
      summary: Historical Index Values for index definition
      tags:
      - Indexes
  /v1/indexes/{index_id}/timeseries:
    get:
      parameters:
      - description: ""
        explode: false
        in: path
        name: index_id
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of requested timeseries period (e.g. `5SEC` or `1DAY`)
        explode: true
        in: query
        name: period_id
        required: true
        schema:
          type: string
        style: form
      - description: Timeseries starting time in ISO 8601
        explode: true
        in: query
        name: time_start
        required: true
        schema:
          type: string
        style: form
      - description: Timeseries ending time in ISO 8601
        explode: true
        in: query
        name: time_end
        required: true
        schema:
          type: string
        style: form
      - description: "Amount of items to return (optional, mininum is 1, maximum is\
          \ 100000, default value is 100, if the parameter is used then every 100\
          \ output items are counted as one request)"
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                  - time_period_start: 2024-09-05T08:00:00+00:00
                    time_period_end: 2024-09-05T09:00:00+00:00
                    time_open: 2024-09-05T08:00:44+00:00
                    time_close: 2024-09-05T08:59:44+00:00
                    value_open: 57146.1153570673
                    value_high: 57210.0651836076
                    value_low: 56950.4558254606
                    value_close: 56993.5152800002
                    value_count: 0
                  - time_period_start: 2024-09-05T09:00:00+00:00
                    time_period_end: 2024-09-05T10:00:00+00:00
                    time_open: 2024-09-05T09:00:44+00:00
                    time_close: 2024-09-05T09:59:59.9+00:00
                    value_open: 57000.6574615287
                    value_high: 57000.6574615287
                    value_low: 56650.5866347198
                    value_close: 56787.2920819528
                    value_count: 0
                  - time_period_start: 2024-09-05T10:00:00+00:00
                    time_period_end: 2024-09-05T11:00:00+00:00
                    time_open: 2024-09-05T10:00:00+00:00
                    time_close: 2024-09-05T10:59:59.9+00:00
                    value_open: 56787.2920819528
                    value_high: 56788.3686345929
                    value_low: 56786.7251004355
                    value_close: 56787.2066526585
                    value_count: 0
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexTimeseriesItem"
                type: array
            application/json:
              examples:
                Example response:
                  value:
                  - time_period_start: 2024-09-05T08:00:00+00:00
                    time_period_end: 2024-09-05T09:00:00+00:00
                    time_open: 2024-09-05T08:00:44+00:00
                    time_close: 2024-09-05T08:59:44+00:00
                    value_open: 57146.1153570673
                    value_high: 57210.0651836076
                    value_low: 56950.4558254606
                    value_close: 56993.5152800002
                    value_count: 0
                  - time_period_start: 2024-09-05T09:00:00+00:00
                    time_period_end: 2024-09-05T10:00:00+00:00
                    time_open: 2024-09-05T09:00:44+00:00
                    time_close: 2024-09-05T09:59:59.9+00:00
                    value_open: 57000.6574615287
                    value_high: 57000.6574615287
                    value_low: 56650.5866347198
                    value_close: 56787.2920819528
                    value_count: 0
                  - time_period_start: 2024-09-05T10:00:00+00:00
                    time_period_end: 2024-09-05T11:00:00+00:00
                    time_open: 2024-09-05T10:00:00+00:00
                    time_close: 2024-09-05T10:59:59.9+00:00
                    value_open: 56787.2920819528
                    value_high: 56788.3686345929
                    value_low: 56786.7251004355
                    value_close: 56787.2066526585
                    value_count: 0
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexTimeseriesItem"
                type: array
            text/json:
              examples:
                Example response:
                  value:
                  - time_period_start: 2024-09-05T08:00:00+00:00
                    time_period_end: 2024-09-05T09:00:00+00:00
                    time_open: 2024-09-05T08:00:44+00:00
                    time_close: 2024-09-05T08:59:44+00:00
                    value_open: 57146.1153570673
                    value_high: 57210.0651836076
                    value_low: 56950.4558254606
                    value_close: 56993.5152800002
                    value_count: 0
                  - time_period_start: 2024-09-05T09:00:00+00:00
                    time_period_end: 2024-09-05T10:00:00+00:00
                    time_open: 2024-09-05T09:00:44+00:00
                    time_close: 2024-09-05T09:59:59.9+00:00
                    value_open: 57000.6574615287
                    value_high: 57000.6574615287
                    value_low: 56650.5866347198
                    value_close: 56787.2920819528
                    value_count: 0
                  - time_period_start: 2024-09-05T10:00:00+00:00
                    time_period_end: 2024-09-05T11:00:00+00:00
                    time_open: 2024-09-05T10:00:00+00:00
                    time_close: 2024-09-05T10:59:59.9+00:00
                    value_open: 56787.2920819528
                    value_high: 56788.3686345929
                    value_low: 56786.7251004355
                    value_close: 56787.2066526585
                    value_count: 0
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexTimeseriesItem"
                type: array
            application/x-msgpack:
              examples:
                Example response:
                  value:
                  - time_period_start: 2024-09-05T08:00:00+00:00
                    time_period_end: 2024-09-05T09:00:00+00:00
                    time_open: 2024-09-05T08:00:44+00:00
                    time_close: 2024-09-05T08:59:44+00:00
                    value_open: 57146.1153570673
                    value_high: 57210.0651836076
                    value_low: 56950.4558254606
                    value_close: 56993.5152800002
                    value_count: 0
                  - time_period_start: 2024-09-05T09:00:00+00:00
                    time_period_end: 2024-09-05T10:00:00+00:00
                    time_open: 2024-09-05T09:00:44+00:00
                    time_close: 2024-09-05T09:59:59.9+00:00
                    value_open: 57000.6574615287
                    value_high: 57000.6574615287
                    value_low: 56650.5866347198
                    value_close: 56787.2920819528
                    value_count: 0
                  - time_period_start: 2024-09-05T10:00:00+00:00
                    time_period_end: 2024-09-05T11:00:00+00:00
                    time_open: 2024-09-05T10:00:00+00:00
                    time_close: 2024-09-05T10:59:59.9+00:00
                    value_open: 56787.2920819528
                    value_high: 56788.3686345929
                    value_low: 56786.7251004355
                    value_close: 56787.2066526585
                    value_count: 0
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexTimeseriesItem"
                type: array
          description: successful operation
      summary: Timeseries Index Value
      tags:
      - Indexes
  /v1/indexdef/multiasset:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
            application/x-msgpack:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
          description: successful operation
      summary: Get all multi-asset weights
      tags:
      - Indexes
  /v1/indexdef/multiasset/{index_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: index_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
            application/x-msgpack:
              schema:
                items:
                  $ref: "#/components/schemas/Models.IndexMultiAssetWeight"
                type: array
          description: successful operation
      summary: Get multi-asset weights for specific index
      tags:
      - Indexes
components:
  schemas:
    Models.IndexDefinitionSnapshotEntry:
      additionalProperties: false
      example:
        index_id: index_id
        value: 0.8008281904610115
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        index_id:
          nullable: true
          type: string
        timestamp:
          format: date-time
          type: string
        value:
          format: double
          type: number
      type: object
    Models.IndexIdentifier:
      additionalProperties: false
      description: Represents an index id
      example:
        id: id
      properties:
        id:
          description: Index ID
          nullable: true
          type: string
      type: object
    Models.IndexMultiAssetWeight:
      additionalProperties: false
      example:
        assetId: assetId
        indexId: indexId
        weight: 0.8008281904610115
      properties:
        indexId:
          nullable: true
          type: string
        assetId:
          nullable: true
          type: string
        weight:
          format: double
          type: number
      type: object
    Models.IndexTimeseriesItem:
      additionalProperties: false
      description: Represents a timeseries item with value information.
      example:
        time_period_end: 2000-01-23T04:56:07.000+00:00
        value_open: 0.8008281904610115
        time_open: 2000-01-23T04:56:07.000+00:00
        value_close: 5.962133916683182
        value_high: 6.027456183070403
        time_close: 2000-01-23T04:56:07.000+00:00
        value_low: 1.4658129805029452
        time_period_start: 2000-01-23T04:56:07.000+00:00
        value_count: 5
      properties:
        time_period_start:
          description: Gets or sets the start time of the time period.
          format: date-time
          type: string
        time_period_end:
          description: Gets or sets the end time of the time period.
          format: date-time
          type: string
        time_open:
          description: Gets or sets the time when the value opened.
          format: date-time
          nullable: true
          type: string
        time_close:
          description: Gets or sets the time when the value closed.
          format: date-time
          nullable: true
          type: string
        value_open:
          description: Gets or sets the opening value.
          format: double
          nullable: true
          type: number
        value_high:
          description: Gets or sets the highest value during the time period.
          format: double
          nullable: true
          type: number
        value_low:
          description: Gets or sets the lowest value during the time period.
          format: double
          nullable: true
          type: number
        value_close:
          description: Gets or sets the closing value.
          format: double
          nullable: true
          type: number
        value_count:
          description: Gets or sets the number of values during the time period.
          format: int64
          type: integer
      type: object
    Models.IndexValue:
      additionalProperties: false
      example:
        composition:
        - component_id: component_id
          component_value: 6.027456183070403
        - component_id: component_id
          component_value: 6.027456183070403
        value: 0.8008281904610115
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        timestamp:
          format: date-time
          type: string
        value:
          format: double
          type: number
        composition:
          items:
            $ref: "#/components/schemas/Models.IndexValueComponent"
          nullable: true
          type: array
      type: object
    Models.IndexValueComponent:
      additionalProperties: false
      example:
        component_id: component_id
        component_value: 6.027456183070403
      properties:
        component_id:
          nullable: true
          type: string
        component_value:
          format: double
          type: number
      type: object
  securitySchemes:
    APIKey:
      description: API Key is required to access the endpoints
      in: header
      name: Authorization
      type: apiKey
    JWT:
      bearerFormat: JWT
      description: "JWT Authorization header using the Bearer scheme. Example: \"\
        Bearer {token}\""
      scheme: bearer
      type: http
